name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Pack SimConnect.NET
              run: dotnet pack src/SimConnect.NET/SimConnect.NET.csproj \
                  --no-build \
                  --configuration Release \
                  --output ./artifacts

            - name: Upload package artifact
              uses: actions/upload-artifact@v4
              with:
                  name: simconnectnet-packages
                  path: ./artifacts/*.nupkg
